### ISSUE TITLE
Home Star Crash

### ISSUE THREAD

**Issue by cellproductions** [cellproductions/7dRTS#12]
Anything that uses the home star in the Player class (Player.star) will crash or cause unknown behaviour once the player in question loses it to another player.
Easy fix, move the home star to the next available star for that player, or do some kind of check each time it is used.

**Comment by Hanzallah** [comment]
Can you clarify what methods use the home star? Are the thing  that use the home star only in the player class?

**Comment by cellproductions** [comment]
It's the "startingStar" field belonging to the Player class. Since it's public it can be used from basically anywhere. It's been 5 years since this was made (poorly) so there's not much more information I can give you.

**Comment by Hanzallah** [comment]
So if I basically make it private then it would be fixed?

**Comment by cellproductions** [comment]
Most definitely not. It's still in use by a number of other things I imagine.

**Comment by burneyh** [comment]
Is this issue still not solved after my pull request because it is still marked open?

**Comment by CalciumKid** [comment]
Fixed in 8ccef52
